#!/home/tmd/PycharmProjects/Weather_for_IP/venv/bin/python
import sys
import os

os.environ["API_KEY"] = 'ca0f5103f17a4b799e2103453222205'
sys.path.insert(0, '/home/tmd/PycharmProjects/Weather_for_IP')
activate_this = str(os.path.dirname(sys.executable)) + '/activate_this.py'
with open(activate_this) as f:
    code = compile(f.read(), activate_this, 'exec')
    exec(code, dict(__file__=activate_this))

from gps_coordinates import get_coordinates
from weather_api_service import get_weather
from weather_formatter import weather_short_format

if __name__ == '__main__':
    coordinates = get_coordinates()
    weather = get_weather(coordinates)
    weather_short_format(weather)
